#!/usr/bin/env ruby

commands = []

Command = Struct.new(:id, :title, :description)

Dir['src/features/*.ts'].each do |file|
  contents = File.read(file)
  contents.scan(/((?:\s*\/\/.*\n)+)\s*id:\s*'([^']+)',\s*\n\s*title:\s*'([^']+)'/).each do |description, id, title|
    commands << Command.new(id, title, description.gsub(/^\s*\/\/\s*/, '').gsub(/\s+/, ' ').strip)
  end
end

command_list = []

commands.sort_by! { |command| command.title.downcase }
commands.each do |command|
  command_list << "* <a name='#{command.id}'></a>**#{command.title}** — #{command.description}"
end

readme = File.read('README.md')
readme = readme.gsub(/(<!--\s*begin-command-list\s*-->).*(<!--\s*end-command-list\s*-->)/m) {
  $1 + "\n\n" + command_list.join("\n") + "\n\n" + $2
}
File.write('README.md', readme)